name: femnist
dataset: femnist
model: cnn_femnist
numb_labels: 62
provider:
  _target_: banditdl.data.providers.FemnistProvider
partitioner:
  _target_: banditdl.data.partitioning.NaturalOwnerPartitionStrategy
  writers_limit: null
