defaults:
  - dataset: mnist
  - topology: dynamic
  - sampler: uniform
  - adversary: none
  - aggregator: mean
  - heterogeneity: alpha0.5
  - optimization: opt_mnist
  - evaluation: evaluation
  - _self_
  - override

seed: 123
device: cpu

hydra:
  run:
    dir: .hydra_runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: .hydra_multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
